#pragma once

#define D_SCREEN_WIDTH 800
#define D_SCREEN_HEIGHT 620

#define RSC_NPC_ADAM_SPRITE "./PlayerTextures/Adam_16x16.png"
#define RSC_MAP1_SPRITE "./Maps/KlasseBottomLayer.png"
#define RSC_MAP1_SPRITE_TOP_LAYER "./Maps/KlasseTopLayer.png"
#define RSC_MAP2_SPRITE "./Maps/SchuleBottomLayer.png"
#define RSC_MAP2_SPRITE_TOP_LAYER "./Maps/SchuleTopLayer.png"

#define RSC_MAP3_SPRITE "./Maps/WieseABSBottom.png"
#define RSC_MAP3_SPRITE_TOP_LAYER "./Maps/WieseABSTop.png"
#define RSC_BANDIT_SPRITE "./EnemyTextures/BanditSpritesheet.png"
#define RSC_ANGRY_SPROUT_SPRITE "./EnemyTextures/SproutSheet.png"
#define RSC_NPC_AMELIA_SPRITE "./PlayerTextures/Amelia_16x16.png"
#define RSC_FONT_ARIAL "./Fonts/arial.ttf"
#define RSC_GAME_OVER_SCREEN "./OtherTextures/GameOverScreen.png"
#define RSC_BACKGROUND_OF_TITLESCREEN "./OtherTextures/TitlescreenBackground.png"
#define RSC_BACKGROUND_OF_SELECTSAVEFILE "./OtherTextures/SelectSaveFileBackground.png"
#define RSC_BACKGROUND_OF_TEXTBOX "./OtherTextures/TextboxForNPCs.png"
#define RSC_NPC_ALEX_SPRITE "./PlayerTextures/Alex_16x16.png"
#define RSC_NPC_BOB_SPRITE "./PlayerTextures/Bob_16x16.png"
#define RSC_NPC_LUKE_SPRITE "./PlayerTextures/Luke_16x16.png"
#define RSC_NPC_FRED_SPRITE "./PlayerTextures/Fred_16x16.png"
#define RSC_NPC_ANDREAS_SPRITE "./PlayerTextures/ANDREAS_16x16.png"
#define RSC_NPC_JOHN_SPRITE "./PlayerTextures/John_16x16.png"
#define RSC_NPC_KEVIN_SPRITE "./PlayerTextures/Kevin.png"
#define RSC_FONT_PIXELSPLITTER "./Fonts/PixelSplitter.ttf"
#define RSC_PLAYER_SPRITE "./PlayerTextures/Adventurer Sprite Sheet v1.1.png"

#define RSC_HUD_LAYER "./OtherTextures/HUD.png"
#define RSC_COIN_SPRITE "./OtherTextures/coin_16x16.png"
#define RSC_NPC_BOOK_SPRITE "./OtherTextures/book.png"
#define RSC_BULLET_SPRITE "./EnemyTextures/Bandit_Bullet_extended.png"
#define RSC_COVID_PROJECTILE_SPRITE "./EnemyTextures/coronaProjektil.png"
#define RSC_IK_CHARAKTER_SPRITE "./PlayerTextures/Adam_16x16.png"
#define RSC_IK_GEOMETRY_IMAGE "./IKTextures/Geometry.png"
#define RSC_IK_BORDER_IMAGE_OUTLINE "./IKTextures/Rand.png"
#define RSC_IK_MEMBRAN_1_IMAGE "./IKTextures/Membran 1.png"
#define RSC_IK_ORGANS_IMAGE "./IKTextures/MergedOrgans.png"
#define RSC_IK_BACKGROUND_IMAGE "./IKTextures/Membran 2.png"
#define RSC_IK_BLOCKER_IMAGE "./IKTextures/Blocker.png"
#define RSC_IK_ENEMY_SPRITE "./EnemyTextures/CovidEnemy.png"